### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by hypnoglow**
The main problem is a memory leak caused by infinite recursion.

This PR:
- Adds profiling
- Fixes memory leak
- Adds a few benchmarks

### CODE REVIEW

**Comment by hypnoglow** [comment]
It seems that CI failed because docker credentials are not valid for some reason.

**Comment by caarlos0** [comment]
cc/ @diogonicoleti

**Comment by diogonicoleti** [comment]
@hypnoglow can you fix this lint warnings before we merge your PR?
```
main.go:116:23:warning: error return value not checked (defer resp.Body.Close()) (errcheck)
main.go:99:2:warning: should use for range instead of for { select {} } (S1000) (megacheck)
```

**Comment by hypnoglow** [comment]
@diogonicoleti Done

**Comment by diogonicoleti** [comment]
@hypnoglow fyi: https://github.com/ContaAzul/hystrix_exporter/releases/tag/v0.0.4

**Pull request merged**
